<?php

declare(strict_types=1);

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Vite;
use Symfony\Component\HttpFoundation\Response;

/**
 * Appends defense-in-depth security headers to every web response.
 *
 * This is the **golden reference** for the fleet, generalized. Fleet-app-specification §5
 * mandates it as a **MUST**: a final `SecurityHeaders` middleware appended to the
 * `web` group, with a nonce-based CSP (no `unsafe-inline`/`unsafe-eval` on
 * `script-src`). It is NOT byte-identical fleet-wide — see wiki/security/
 * application-security.md's divergence note — the *only* apps-may-differ points
 * are marked TUNE POINT below; every other directive, especially `script-src`,
 * MUST stay uniform.
 *
 *   TUNE POINT 1 — font-src / style-src webfont host: this copy defaults to
 *   self-hosted fonts only (`'self' data:`), the fleet baseline (every app
 *   uses it verbatim). An app that loads a webfont CDN allow-lists that exact
 *   host in BOTH directives (e.g. acme -> https://fonts.bunny.net) and registers the
 *   deviation in fleet-app-specification §7 (see A-06).
 *
 *   TUNE POINT 2 — connect-src / Reverb: the CSP builder below reads Reverb's
 *   config and adds its ws(s) origin to `connect-src` when present, collapsing
 *   to plain `'self'` when the app has no Reverb config. Safe to copy verbatim
 *   into every app, Reverb or not.
 *
 * Headers:
 *   - Strips X-Powered-By (PHP's expose_php runtime leak).
 *   - Content-Security-Policy: non-local envs only. CSP and the Vite dev server
 *     fight constantly — Vite serves HMR over a separate origin, injects dynamic
 *     styles/scripts from changing ports, uses blob: workers, and chunk URLs that
 *     aren't knowable ahead of time. The header is a production protection; dev
 *     doesn't need it.
 *   - Strict-Transport-Security: 1 year + subdomains (production only).
 *   - X-Frame-Options: DENY (no framing).
 *   - Referrer-Policy: strict-origin-when-cross-origin (default modern).
 *   - Permissions-Policy: deny camera/microphone/geolocation/payment by default.
 *   - X-Content-Type-Options: nosniff.
 *
 * Clears the OWASP ZAP baseline header findings — anti-clickjacking [10020],
 * X-Content-Type-Options [10021], X-Powered-By leak [10037], CSP [10038],
 * Permissions-Policy [10063]: CSP/HSTS in production, the rest in every env.
 */
final class SecurityHeaders
{
    public function handle(Request $request, Closure $next): Response
    {
        /** @var Response $response */
        $response = $next($request);

        $headers = $response->headers;

        // PHP's expose_php leaks the runtime via X-Powered-By; strip it at the
        // SAPI level (php-fpm) and from the response bag.
        if (function_exists('header_remove')) {
            header_remove('X-Powered-By');
        }
        $headers->remove('X-Powered-By');

        // Never clobber a header a route set deliberately.
        foreach ($this->securityHeaders() as $name => $value) {
            if (! $headers->has($name)) {
                $headers->set($name, $value);
            }
        }

        return $response;
    }

    /**
     * The header set to apply. CSP is emitted outside local only (Vite HMR), and
     * HSTS in production only (it is meaningless without TLS).
     *
     * @return array<string, string>
     */
    private function securityHeaders(): array
    {
        $headers = [
            'X-Frame-Options' => 'DENY',
            'X-Content-Type-Options' => 'nosniff',
            'Referrer-Policy' => 'strict-origin-when-cross-origin',
            'Permissions-Policy' => 'camera=(), microphone=(), geolocation=(), payment=()',
        ];

        if (! app()->environment('local')) {
            $headers['Content-Security-Policy'] = $this->csp();
        }

        if (app()->isProduction()) {
            $headers['Strict-Transport-Security'] = 'max-age=31536000; includeSubDomains';
        }

        return $headers;
    }

    /**
     * Build the CSP. Reverb's wss origin comes from the reverb config — the
     * canonical surface for REVERB_HOST/REVERB_SCHEME — so this stays
     * config-cache safe and collapses to just 'self' for apps without Reverb.
     * Only emitted in non-local envs (see `securityHeaders()`).
     */
    private function csp(): string
    {
        // The per-request nonce generated by Vite::useCspNonce() in
        // AppServiceProvider::boot() (standards/laravel/app/Providers/
        // AppServiceProvider.php). Vite stamps it on the <script>/<style>/
        // <link> tags it emits; any hand-written inline <script> in
        // app.blade.php must carry it explicitly. Lets script-src drop
        // 'unsafe-inline'. Empty-string fallback keeps the directive valid on
        // the rare response that renders before boot (matches nothing).
        $nonce = (string) Vite::cspNonce();

        $options = (array) config('reverb.apps.apps.0.options', []);
        $reverbHost = (string) ($options['host'] ?? '');
        $reverbScheme = (string) ($options['scheme'] ?? 'https');
        $reverbPort = (string) ($options['port'] ?? '');
        $wsScheme = $reverbScheme === 'https' ? 'wss' : 'ws';

        $connectSrc = "'self'";
        if ($reverbHost !== '') {
            $connectSrc .= " {$wsScheme}://{$reverbHost}";
            if ($reverbPort !== '' && $reverbPort !== '443' && $reverbPort !== '80') {
                $connectSrc .= " {$wsScheme}://{$reverbHost}:{$reverbPort}";
            }
        }

        return implode('; ', [
            "default-src 'self'",
            "base-uri 'self'",
            "form-action 'self'",
            "frame-ancestors 'none'",
            "img-src 'self' data: blob:",
            // TUNE POINT 1 (font-src): fleet default is self-hosted fonts only.
            // An app loading a webfont CDN allow-lists the exact host here AND
            // in style-src below (e.g. acme: "'self' data: https://fonts.bunny.net"),
            // and registers the deviation as fleet-app-specification §7 A-06.
            "font-src 'self' data:",
            // style-src KEEPS 'unsafe-inline': Radix/@dnd-kit inject dynamic
            // inline style ATTRIBUTES at runtime, which CSP nonces/hashes
            // cannot cover. Removing it breaks the UI — accepted fleet-wide as
            // a documented tradeoff (can't-pursue). TUNE POINT 1
            // (webfont host) applies here too if font-src was extended above.
            "style-src 'self' 'unsafe-inline'",
            // script-src: 'unsafe-eval' omitted (SEC-001) AND 'unsafe-inline'
            // dropped in favour of a per-request nonce . The @vite tags
            // are stamped by Vite::useCspNonce(); any hand-written inline
            // <script> in app.blade.php carries the nonce explicitly. This is
            // the real XSS win — an injected <script> without the nonce won't
            // execute. NOT a tune point — MUST stay nonce-based, no
            // unsafe-inline/unsafe-eval, on every app.
            "script-src 'self' 'nonce-{$nonce}'",
            "connect-src {$connectSrc}",
            "object-src 'none'",
        ]);
    }
}
